"""
Chapter 01 — run via the Python API and verify against the golden master.

Steps:
  1. Load `rules.json` (generated by build_rules.py) into a RuleSet.
  2. Harmonize input.csv -> output.csv with `harmonize_file`.
  3. Assert the result equals the pinned `expected_output.csv`.

`harmonize_file` keeps every input column AND appends the target columns, plus
the `source dataset` / `original_id` metadata columns. So this example's
`expected_output.csv` is the *full* table. (The CLI variant, by contrast, emits
only the target columns — see run_cli.sh and the README.)
"""

import sys
from pathlib import Path

from harmonization_framework import RuleSet
from harmonization_framework.harmonize import harmonize_file

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "_shared"))
from check_output import assert_matches  # noqa: E402


def main() -> None:
    rules = RuleSet()
    rules.load(str(HERE / "rules.json"), clean=True)

    harmonize_file(
        input_path=str(HERE / "input.csv"),
        output_path=str(HERE / "output.csv"),
        rules=rules,
        dataset_name="hello",
    )

    assert_matches(HERE / "output.csv", HERE / "expected_output.csv")


if __name__ == "__main__":
    main()
